name: simSPI-mac
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - configparser
  - coverage
  - h5py
  - mdtraj
  - mrcfile
  - numba
  - numpy
  - pip
  - pyfftw
  - pytest
  - pytest-cov
  - pytorch=1.9.0
  - pip:
    - geomstats
    - git+https://github.com/compSPI/compSPI.git
    - git+https://github.com/compSPI/ioSPI.git
    - pytorch3d
    - raster_geometry
    - starfile
