name: 'Execute in Docker container'
description: 'Execute command in Docker container'
inputs:
  tag:
    description: 'Tag version of the Docker container to use'
    required: true
    default: 'latest'
  command:
    description: 'Command to be execute in Docker container'
    required: true
    default: 'ls -altrh /'
runs:
  using: 'docker'
  image: 'docker://fpoitevi/simspi:test'
  args:
    - ${{ inputs.command }}