# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-actions
name: 'Execute in Docker container'
description: 'Execute command in Docker container'
inputs:
  command: # id of input
    description: 'Command to be execute in Docker container'
    required: true
    default: 'ls /work/*'
runs:
  using: 'docker'
  image: 'docker://fpoitevi/simspi:latest'
  args:
    - ${{ inputs.command }}