name: 'Execute in Docker container'
description: 'Execute command in Docker container'
inputs:
  command:
    description: 'Command to be execute in Docker container'
    required: true
    default: 'ls -a . /opt /work'
runs:
  using: 'docker'
  image: 'docker://fpoitevi/simspi:latest'
  args:
    - ${{ inputs.command }}
  post-entrypoint: 'post-entrypoint.sh'