  # absolute paths
  pdb_file: '/home/luis/simSPI/notebooks/4v6x.pdb'
  metadata_params_file: '/home/luis/simSPI/notebooks/metadata_fields.yaml'
  mrc_keyword: '_randomrot'
  output_dir: '/home/luis/simSPI/notebooks/'
  local_sim_dir: '/home/luis/TEM-simulator_1.3/src/TEM-simulator'

