  pdb_file: './simSPI/notebooks/4v6x.pdb'
  metadata_params_file: './simSPI/notebooks/metadata_fields.yaml'
  mrc_keyword: '_randomrot'
  output_dir: './simSPI/notebooks/'
  local_sim_dir: './TEM-simulator_1.3/src/TEM-simulator'

