name: "Building container and testing simSPI"

on:
  push:
    branches: [master, temsim-test-in-container]
    paths:
      - 'docker/Dockerfile'
      - 'docker/entrypoint.sh'
      - 'environment.yml'
      - 'setup.py'
      - '.github/workflows/build_container.yml'

  pull_request:
    branch: [master]
    paths:
      - 'docker/Dockerfile'
      - 'docker/entrypoint.sh'
      - 'environment.yml'
      - 'setup.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simspi:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Install Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Run linting in container
        run: singularity exec docker://${{ secrets.DOCKER_HUB_USERNAME }}/simspi:latest flake8 simSPI tests

      - name: Run tests in container
        run: singularity exec docker://${{ secrets.DOCKER_HUB_USERNAME }}/simspi:latest pytest --cov-report term --cov-report xml:coverage.xml --cov=simSPI ${{matrix.test-folder}}

      - name: uploading code coverage [codecov]
        if: ${{matrix.python-version == 3.7}}
        run: |
          bash <(curl -s https://codecov.io/bash) -c